# Python package

jobs:

- job: "Test"

  - script: python -m pip install --upgrade pip && pip install -r app/requirements.txt
    displayName: 'Install dependencies'

  - script: |
      pip install pytest
      pytest tests --doctest-modules --junitxml=junit/test-results.xml
    displayName: 'pytest'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '2.7'
      architecture: 'x64'

  - script: python -m pytest app/test.py
    displayName: 'Run tests'
