# Python package

jobs:
- job: Test
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '2.7'
      architecture: 'x64'
  - script: sudo apt-get update  && sudo apt-get install mysql* libmysqlclient-dev python-dev
  - script: python -m pip install --upgrade pip && pip install -r app/requirements.txt
    displayName: 'Install dependencies'
  - script: |
      pip install pytest
      pytest test.py --doctest-modules --junitxml=junit/test-results.xml
    displayName: 'pytest'
    workingDirectory: 'app/'

